// Hybrid search — augments the metadata-driven Step 1 with cosine similarity
// over precomputed section embeddings (documents/embeddings.json, generated by
// scripts/generate-embeddings.mjs). v2 design Phase 4 (docs/v2-design.md §4-A).
//
// Design choices:
// - JS-side cosine over a JSON file is enough at the current 50-doc scale.
//   pgvector / external vector DBs are explicitly deferred until 500+ docs
//   (docs/v2-design.md §6, §10).
// - Hybrid search is BEST-EFFORT: a missing embeddings file, a failed embed
//   API call, or a dimension mismatch all degrade silently back to the
//   metadata-only Step 1. The user must never see a search fail because the
//   vector layer broke.
// - The query embedding is generated with the model name recorded inside the
//   embeddings file — using llmConfig.embeddingModel would risk mixing models
//   between query and index, which silently destroys similarity quality.

import fs from "node:fs/promises";
import path from "node:path";
import { embed } from "./workers-ai";
import { isLlmConfigured, llmConfig } from "./llm-config";

interface EmbeddingItem {
  doc_id: string;
  section_id: string;
  section_title: string;
  vector: number[];
}

interface EmbeddingsFile {
  model: string;
  dim: number;
  count: number;
  items: EmbeddingItem[];
}

export type EmbeddingsLoad =
  | { available: true; data: EmbeddingsFile }
  | { available: false; reason: string };

const ROOT = process.cwd();
const EMBEDDINGS_PATH = path.join(ROOT, "documents", "embeddings.json");

let cache: Promise<EmbeddingsLoad> | null = null;

export async function loadEmbeddings(): Promise<EmbeddingsLoad> {
  if (cache) return cache;
  cache = (async (): Promise<EmbeddingsLoad> => {
    try {
      const raw = await fs.readFile(EMBEDDINGS_PATH, "utf8");
      const data = JSON.parse(raw) as EmbeddingsFile;
      if (!Array.isArray(data.items) || data.items.length === 0) {
        return { available: false, reason: "embeddings.json has no items" };
      }
      if (!Number.isInteger(data.dim) || data.dim <= 0) {
        return { available: false, reason: "embeddings.json missing dim" };
      }
      return { available: true, data };
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      return { available: false, reason: msg };
    }
  })();
  return cache;
}

export function cosine(a: number[], b: number[]): number {
  if (a.length !== b.length || a.length === 0) return 0;
  let dot = 0;
  let na = 0;
  let nb = 0;
  for (let i = 0; i < a.length; i++) {
    const av = a[i];
    const bv = b[i];
    dot += av * bv;
    na += av * av;
    nb += bv * bv;
  }
  if (na === 0 || nb === 0) return 0;
  return dot / (Math.sqrt(na) * Math.sqrt(nb));
}

export interface VectorHit {
  doc_id: string;
  section_id: string;
  section_title: string;
  score: number;
}

export async function vectorSearch(
  query: string,
  k = 10,
): Promise<VectorHit[] | null> {
  const loaded = await loadEmbeddings();
  if (!loaded.available) {
    // No index → caller falls back to metadata-only Step 1.
    return null;
  }
  if (!isLlmConfigured()) {
    // Can't embed without Workers AI credentials — fail soft so the rest of
    // Step 1 still runs on metadata alone.
    return null;
  }
  // Embed the query with the exact model recorded in the embeddings file, so
  // the query and index vectors always come from the same model.
  const modelName = loaded.data.model || llmConfig.embeddingModel;

  let queryVec: number[];
  try {
    const [vec] = await embed([query], modelName);
    queryVec = vec ?? [];
  } catch (e) {
    console.warn(
      "[hybrid-search] embed failed, falling back to metadata-only:",
      e instanceof Error ? e.message : e,
    );
    return null;
  }

  if (queryVec.length !== loaded.data.dim) {
    console.warn(
      `[hybrid-search] dimension mismatch (query=${queryVec.length} index=${loaded.data.dim}, model=${modelName}); falling back.`,
    );
    return null;
  }

  const scored = loaded.data.items.map((it) => ({
    doc_id: it.doc_id,
    section_id: it.section_id,
    section_title: it.section_title,
    score: cosine(queryVec, it.vector),
  }));
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, k);
}

// Renders top-k vector hits as a prompt block. Kept here (rather than inlined
// into search.ts) so the block format stays close to the data shape and can
// be unit-tested without spinning up the whole search pipeline.
export function renderVectorBlock(hits: VectorHit[]): string {
  if (hits.length === 0) return "";
  const lines = hits.map(
    (h, i) =>
      `${i + 1}. [${h.doc_id}/${h.section_id}] ${h.section_title}  (score=${h.score.toFixed(3)})`,
  );
  return `# ベクトル類似度上位セクション（参考）
質問に意味的に近いセクションを参考情報として提示する。最終判断は下記のドキュメント一覧と合わせて行うこと。
${lines.join("\n")}

`;
}
