// Bundles the document corpus into lib/generated/corpus.ts.
//
// Why: Cloudflare Workers (the OpenNext deployment target) have no project
// filesystem at runtime — the only `fs` reads OpenNext supports are the
// Next.js-internal manifest reads it patches itself. So documents/ cannot be
// read with fs.readFile in the Worker. This script embeds index.json plus
// every section .md file into a plain TS module that gets compiled into the
// Worker bundle. Node deployments (next dev / next start / Vercel) ignore the
// bundle and keep reading documents/ off disk (see lib/document-utils.ts).
//
// The output is git-ignored and regenerated by `postinstall` and `cf:build`.
// Run manually with: node scripts/build-corpus.mjs

import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const INDEX_REL = "documents/index.json";

const indexRaw = fs.readFileSync(path.join(ROOT, INDEX_REL), "utf8");
const index = JSON.parse(indexRaw);
if (!Array.isArray(index)) {
  throw new Error(`${INDEX_REL} is not a JSON array`);
}

// Map of repo-root-relative POSIX path -> file contents.
const corpus = { [INDEX_REL]: indexRaw };
for (const doc of index) {
  if (typeof doc?.path !== "string" || !doc.path) {
    throw new Error(`${INDEX_REL}: document "${doc?.id}" has no path`);
  }
  const abs = path.join(ROOT, doc.path);
  if (!fs.existsSync(abs)) {
    throw new Error(`${INDEX_REL}: "${doc.path}" listed but missing on disk`);
  }
  corpus[doc.path] = fs.readFileSync(abs, "utf8");
}

// Sorted keys -> stable, diff-friendly output across regenerations.
const sorted = {};
for (const key of Object.keys(corpus).sort()) sorted[key] = corpus[key];

const body = `// AUTO-GENERATED by scripts/build-corpus.mjs — do not edit by hand.
// Regenerate after changing documents/:  node scripts/build-corpus.mjs
//
// Build-time snapshot of the document corpus, keyed by repo-root-relative
// path. Consumed only on runtimes without a project filesystem (Cloudflare
// Workers / OpenNext); Node deployments read documents/ off disk instead.
export const corpus: Record<string, string> = ${JSON.stringify(sorted)};
`;

const outDir = path.join(ROOT, "lib", "generated");
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, "corpus.ts"), body);

console.log(
  `[build-corpus] lib/generated/corpus.ts — ${Object.keys(sorted).length} entries ` +
    `(${(body.length / 1024).toFixed(0)} KB)`,
);
