// Generates the build artifacts public/corpus.json and
// lib/generated/build-info.ts from documents/.
//
// Why corpus.json: Cloudflare Workers (the OpenNext deployment target) have no
// project filesystem at runtime, so documents/ cannot be read with fs.readFile
// in the Worker. This script writes the corpus (index.json plus every section
// .md file) to public/corpus.json, which `next build` copies into the
// deployment's static assets; the Worker reads it at runtime via the ASSETS
// binding. Serving it from static assets instead of bundling it into the
// Worker script keeps it out of the 3 MiB Worker size budget. Node
// deployments (next dev / next start / Vercel) ignore corpus.json and read
// documents/ off disk (see lib/document-utils.ts).
//
// Both outputs are git-ignored and regenerated by `postinstall` and `cf:build`.
// Run manually with: node scripts/build-corpus.mjs

import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";

const ROOT = process.cwd();
const INDEX_REL = "documents/index.json";

const indexRaw = fs.readFileSync(path.join(ROOT, INDEX_REL), "utf8");
const index = JSON.parse(indexRaw);
if (!Array.isArray(index)) {
  throw new Error(`${INDEX_REL} is not a JSON array`);
}

// Map of repo-root-relative POSIX path -> file contents.
const corpus = { [INDEX_REL]: indexRaw };
for (const doc of index) {
  if (typeof doc?.path !== "string" || !doc.path) {
    throw new Error(`${INDEX_REL}: document "${doc?.id}" has no path`);
  }
  const abs = path.join(ROOT, doc.path);
  if (!fs.existsSync(abs)) {
    throw new Error(`${INDEX_REL}: "${doc.path}" listed but missing on disk`);
  }
  corpus[doc.path] = fs.readFileSync(abs, "utf8");
}

// Sorted keys -> stable, diff-friendly output across regenerations.
const sorted = {};
for (const key of Object.keys(corpus).sort()) sorted[key] = corpus[key];

// Build-time snapshot of the document corpus, keyed by repo-root-relative
// path. Written to public/ so `next build` copies it into the deployment's
// static assets; the Worker fetches it at runtime via the ASSETS binding.
const corpusJson = JSON.stringify(sorted);
const publicDir = path.join(ROOT, "public");
fs.mkdirSync(publicDir, { recursive: true });
fs.writeFileSync(path.join(publicDir, "corpus.json"), corpusJson);

console.log(
  `[build-corpus] public/corpus.json — ${Object.keys(sorted).length} entries ` +
    `(${(corpusJson.length / 1024).toFixed(0)} KB)`,
);

const outDir = path.join(ROOT, "lib", "generated");
fs.mkdirSync(outDir, { recursive: true });

// --- build identifier -----------------------------------------------------
// BUILD_NUMBER is the git commit count — the conventional deterministic build
// number. (CI run counters are the other common source, but Cloudflare Workers
// Builds exposes no monotonic counter.)
// Cloudflare Workers Builds checks out a shallow clone, where `rev-list --count`
// only sees the fetched depth. We deepen the clone with `fetch --unshallow`
// first; if that is not possible (no network / no remote) we fall back to a
// baseline so the displayed number never regresses to a misleading value.
const BUILD_BASELINE = 86;

function git(args) {
  return execSync(`git ${args}`, {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  }).trim();
}

let buildNumber = BUILD_BASELINE;
try {
  let shallow = git("rev-parse --is-shallow-repository") === "true";
  if (shallow) {
    // Deepen the clone so the commit count reflects real history rather than
    // the truncated fetch depth. Best-effort: a missing remote or no network
    // leaves it shallow and we fall back to the baseline below.
    try {
      git("fetch --unshallow --quiet");
      shallow = git("rev-parse --is-shallow-repository") === "true";
    } catch {
      // keep shallow
    }
  }
  const count = Number.parseInt(git("rev-list --count HEAD"), 10);
  if (!shallow && Number.isFinite(count)) buildNumber = count;
} catch {
  // git unavailable (e.g. deploying from a source tarball) — keep the baseline.
}

const buildInfoBody = `// AUTO-GENERATED by scripts/build-corpus.mjs — do not edit by hand.
// Build identifier surfaced in the UI footer. BUILD_NUMBER is the git commit
// count; BUILD_DATE is the build date and time (JST, "YYYY-MM-DD HH:MM").
export const BUILD_NUMBER = ${buildNumber};
export const BUILD_DATE = ${JSON.stringify(
  new Date().toLocaleString("sv-SE", { timeZone: "Asia/Tokyo" }).slice(0, 16),
)};
`;
fs.writeFileSync(path.join(outDir, "build-info.ts"), buildInfoBody);

console.log(`[build-corpus] lib/generated/build-info.ts — Build ${buildNumber}`);
