#!/usr/bin/env node
// Propose an edit to a v2 document by opening a GitHub PR.
//
// v2 design Phase 5 (docs/v2-design.md §4-E): every documents/ change goes
// through branch + PR so a CODEOWNERS reviewer signs off before content
// reaches main. This script is the simplest possible consumer of lib/github.ts
// and exercises the same path the future chat-edit UI (Phase 6) will use.
//
// Usage:
//   node scripts/propose-edit.mjs <doc-id> <replacement-file>
//                                  [--message "Commit/PR title"]
//                                  [--body "Longer PR description"]
//                                  [--branch "edit/foo"]
//
// Reads:
//   - documents/index.json  (to resolve doc-id → path + title)
//   - replacement-file      (the full new file body — must contain
//                            frontmatter, section markers, etc.)
//
// Requires environment:
//   GITHUB_TOKEN          PAT with `repo` scope
//   GITHUB_REPO_OWNER     (default: afdpfrss)
//   GITHUB_REPO_NAME      (default: document-agent)
//   GITHUB_BASE_BRANCH    (default: main)

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const INDEX_PATH = path.join(ROOT, "documents", "index.json");

function parseArgs(argv) {
  const out = { positional: [], flags: {} };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith("--")) {
      const k = a.slice(2);
      const next = argv[i + 1];
      if (next === undefined || next.startsWith("--")) {
        out.flags[k] = true;
      } else {
        out.flags[k] = next;
        i++;
      }
    } else {
      out.positional.push(a);
    }
  }
  return out;
}

async function loadEnvLocal() {
  try {
    const raw = await fs.readFile(path.join(ROOT, ".env.local"), "utf8");
    for (const line of raw.split("\n")) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (!m) continue;
      let v = m[2];
      if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
        v = v.slice(1, -1);
      }
      if (!process.env[m[1]]) process.env[m[1]] = v;
    }
  } catch {
    // Optional file — env may come from the shell.
  }
}

async function main() {
  await loadEnvLocal();
  const args = parseArgs(process.argv.slice(2));
  if (args.positional.length < 2 || args.flags.help) {
    console.error(
      "Usage: node scripts/propose-edit.mjs <doc-id> <replacement-file> [--message TEXT] [--body TEXT] [--branch NAME]",
    );
    process.exit(args.positional.length < 2 ? 1 : 0);
  }
  const [docId, replacementFile] = args.positional;

  const index = JSON.parse(await fs.readFile(INDEX_PATH, "utf8"));
  const doc = index.find((d) => d.id === docId);
  if (!doc) {
    console.error(`Document not found in index.json: ${docId}`);
    process.exit(1);
  }

  const newContent = await fs.readFile(path.resolve(replacementFile), "utf8");
  const message = String(args.flags.message ?? `Edit: ${doc.title}`);
  const prBody =
    typeof args.flags.body === "string"
      ? args.flags.body
      : `Proposed edit to \`${doc.path}\` (${docId} — ${doc.title}).\n\nGenerated by scripts/propose-edit.mjs.`;

  // Node can't import lib/github.ts directly without a TS loader, so the
  // Octokit dance below mirrors lib/github.ts proposeEdit(). Keep the two
  // in sync when changing branch/commit/PR semantics.
  const { Octokit } = await import("octokit");
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    console.error(
      "GITHUB_TOKEN is not set. Configure a PAT with `repo` scope before running this script.",
    );
    process.exit(1);
  }
  const owner = process.env.GITHUB_REPO_OWNER ?? "afdpfrss";
  const repo = process.env.GITHUB_REPO_NAME ?? "document-agent";
  const baseBranch = process.env.GITHUB_BASE_BRANCH ?? "main";
  const branchName =
    typeof args.flags.branch === "string"
      ? args.flags.branch
      : `edit/${docId}-${Math.floor(Date.now() / 1000)}`;

  const oct = new Octokit({ auth: token });

  const baseRef = await oct.rest.git.getRef({ owner, repo, ref: `heads/${baseBranch}` });
  await oct.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: baseRef.data.object.sha,
  });

  let existingSha;
  try {
    const existing = await oct.rest.repos.getContent({
      owner,
      repo,
      path: doc.path,
      ref: branchName,
    });
    if (!Array.isArray(existing.data) && existing.data.type === "file") {
      existingSha = existing.data.sha;
    }
  } catch (err) {
    if (err?.status !== 404) throw err;
  }

  await oct.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: doc.path,
    message,
    content: Buffer.from(newContent, "utf8").toString("base64"),
    branch: branchName,
    sha: existingSha,
  });

  const pr = await oct.rest.pulls.create({
    owner,
    repo,
    head: branchName,
    base: baseBranch,
    title: message,
    body: prBody,
  });

  console.log(`Branch:  ${branchName}`);
  console.log(`PR #${pr.data.number}: ${pr.data.html_url}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
